name: CI

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:  # permite rodar manualmente pelo botão "Run workflow"

jobs:
  backend:
    name: Backend (Java + Maven)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - run: mvn -B verify

  frontend:
    name: Frontend (Node + Angular)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test --if-present -- --watch=false
      - run: npm run build -- --configuration production

  docker-build:
    name: Docker build (API + Web)
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: es2-api:ci
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: es2-web:ci
