name: CI

on:
  push:
    branches: ["**"]   # roda em qualquer branch
  pull_request:        # roda também em PRs

jobs:
  backend:
    name: Backend (Java + Maven)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend   # ajuste se seu backend estiver em outra pasta
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'          # use 25 se seu projeto precisar
          cache: maven

      - name: Build & Test
        run: mvn -B verify

  frontend:
    name: Frontend (Node + Angular)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend   # ajuste se seu Angular estiver em outra pasta
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Lint (se tiver script)
        run: npm run lint --if-present

      - name: Run tests (se tiver configurado)
        run: npm test --if-present -- --watch=false

      - name: Build production
        run: npm run build -- --configuration production

  docker-build:
    name: Docker build (API + Web)
    runs-on: ubuntu-latest
    needs: [backend, frontend]   # só roda se backend e frontend passarem
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: es2-api:ci

      - name: Build Web image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: es2-web:ci
